### ISSUE TITLE
Composer update does not pick-up plugin updates

### ISSUE THREAD

**Issue by jan-dh** [studioespresso/craft3-navigate#26]
Running `composer update` doesn't pick up any changes in the plugin. 

I'm currently on version `2.0.2`. The admin panel shows me the next releases: 

```
|  2.1.3 	|   21-3-2019	|   
|  2.1.2 	|   20-3-2019	|   
|  2.1.1 	|   20-3-2019	|   
|  2.1.0 	|   18-3-2019	|   
```

**Comment by janhenckens** [comment]
Strange, packagist has those tags so it should work: https://packagist.org/packages/studioespresso/craft-navigate

Could you send me your composer.json & .lock file so I can try to reproduce it?

**Comment by jan-dh** [comment]
Yep, coming your way.

**Comment by janhenckens** [comment]
Your composer.json requires the plugin at exactly 2.0.2:

`"studioespresso/craft-navigate": "2.0.2"`

which is why it isn't picking up the updates through composer. Updates should work through `./craft update` or by updating in the CP. Or you could change the version in your composer.json to `^2.0.0`.

Feel free to ping me if it doesn't work out!
